[![Generated by roxygen2: do not edit by hand]

export"(main)","(parse_description)","(parse_topics)","(process_package)"
importFrom"(aws.sqs,create_queue)","(aws.sqs,delete_msg)","(aws.sqs,receive_msg)","(jsonlite,fromJSON)","(jsonlite,prettify)","(jsonlite,toJSON)","(jsonlite,write_json)","(magrittr, % > %)","(purrr,map)","(purrr,transpose)"
