version: 2.1
orbs:
  datacamp-ecr: datacamp/ecr@1
  datacamp-deploy: datacamp/deploy@2
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - datacamp-ecr/build_and_push_image_to_ecr:
          name: build
          context: org-global
          aws-access-key-id: $OPS_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $OPS_AWS_SECRET_ACCESS_KEY
          account-url: $OPS_ECR_URL
          puller-account-ids: '["301258414863", "487088987264"]'
          pre-build-steps:
            - run:
                name: Build application docker image
                command: |
                  docker login -p ${DOCKERHUB_PASSWORD} -u ${DOCKERHUB_USER} dockerhub.datacamp.com:443
      - datacamp-deploy/deploy: # Staging
          context: org-global
          requires:
            - build
          environment: staging
          aws-access-key-id: $STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $STAGING_AWS_SECRET_ACCESS_KEY
          extra-env: "SERVICE=rdoc-r-worker"
          filters:
            branches:
              only:
                - master
      - datacamp-deploy/deploy: # Production
          context: org-global
          requires:
            - build
          environment: prod
          aws-access-key-id: $PROD_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $PROD_AWS_SECRET_ACCESS_KEY
          extra-env: "SERVICE=rdoc-r-worker"
          filters:
            branches:
              only:
                - master
